### ISSUE TITLE
Add docker capability in pre/post script

### ISSUE THREAD

**Issue by thelittlefireman** [azinchen/duplicacy#11]
Hi,
I make a PR to add docker command in pre and post script. For example, i've got a mysql container and I should execute a `docker exec -it mysql dump` before make a backup.

Thansk

**Comment by azinchen** [comment]
Thanks for effort! Merged both to `master` branch (`edge` docker tag) and `release` branch (`latest` docker tag).

**Comment by azinchen** [comment]
Size of docker images are increased from ~31 MB to ~105 MB, which I don't like.

I prefer to use separate container (like `databack/mysql-backup` and `prodrigestivill/postgres-backup-local`) to backup database to volume and then backup this volume. I don't see additional cases when `/var/run/docker.sock` might be useful inside the backup container and scenario from this PR is worth to increase size of docker image.

**Comment by Akruidenberg** [comment]
When running my script in the container, i''ve got Docker not found error. Also, The container says no script is running in the logs.

**Comment by azinchen** [comment]
@Akruidenberg,

Did you pass '/var/run/docker.sock' to the container?
Could you provide an example of docker-compose.yml file with duplicacy and script file?

**Comment by Akruidenberg** [comment]
```
  duplicacy:
    image: azinchen/duplicacy
    container_name: duplicacy
    restart: unless-stopped
    hostname: duplicacy 
    networks:
      - reverseproxy
    volumes:
      - scrutiny:/data/scrutiny
      - filebrowser:/data/filebrowser
      - $ROOTDIR/duplicacy:/duplicacy
      - $ROOTDIR/scripts/pre/pre.sh:/pre.sh
      - $ROOTDIR/scripts/post/post.sh:/post.sh      
      - /var/run/docker.sock:/var/run/docker.sock      
      - /usr/bin/docker:/usr/bin/docker  
    environment:
      DUPLICACY_PASSWORD: secret
      STORAGE_URL: /duplicacy
      SNAPSHOT_ID: test
      PRE_BACKUP_SCRIPT: /pre.sh
      POST_BACKUP_SCRIPT: /post.sh
      RUN_JOB_IMMEDIATELY: "yes"
```

Example sh script:
```

#!/bin/sh
docker exec nextcloud php occ maintenance:mode --off     
docker start recipes netbootxyz openldap portainer bitwarden firefoxsync jellyfin tvheadend bookstack organizr   
```
```

container logs:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-setupssmtp: executing... ,
[cont-init.d] 10-setupssmtp: exited 0.,
[cont-init.d] 20-init: executing... ,
This folder has already been initialized with duplicacy. Not initializing again,
[cont-init.d] 20-init: exited 0.,
[cont-init.d] 60-createcron: executing... ,
[cont-init.d] 60-createcron: exited 0.,
[cont-init.d] 99-backupimmediately: executing... ,
[cont-init.d] 99-backupimmediately: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
```

script running in container:

```
/pre.sh: line 2: docker: not found
/pre.sh: line 3: docker: not found
/pre.sh: line 4: docker: not found
/pre.sh: line 5: docker: not found
/pre.sh: line 6: docker: not found
```

Duplicati is running fine with the scripts, however.
